'use client';
import {useEffect,useState} from 'react';
import {auth,firebaseEnabled} from '@/lib/firebase';
import {GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged,User} from 'firebase/auth';
type Data={links:any[];payments:any[];keys:any[];events:any[]};
export default function Home(){const [data,setData]=useState<Data>({links:[],payments:[],keys:[],events:[]}),[tab,setTab]=useState('Overview'),[modal,setModal]=useState(false),[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[desc,setDesc]=useState(''),[toast,setToast]=useState(''),[user,setUser]=useState<User|null>(null),[secret,setSecret]=useState('');
async function refresh(){const r=await fetch('/api/demo');const d=await r.json();if(r.ok)setData(d);else notify(d.error)}function notify(s:string){setToast(s);setTimeout(()=>setToast(''),3200)}useEffect(()=>{refresh();if(auth)return onAuthStateChanged(auth,setUser)},[]);
async function action(body:any){const r=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){notify(d.error);return null}await refresh();return d}
async function create(){const d=await action({action:'createLink',title,amount,description:desc});if(d){setModal(false);setTitle('');setAmount('');setDesc('');notify('Payment link created')}}
async function key(){const d=await action({action:'apiKey',label:'Test API key'});if(d){setSecret(d.secret);notify('Key created — copy it now')}}
const total=data.payments.filter(p=>p.status==='SUCCEEDED').reduce((s,p)=>s+p.amount,0);const succeeded=data.payments.filter(p=>p.status==='SUCCEEDED').length;
return <div className="shell"><aside className="sidebar"><div className="brand"><div className="logo">N</div><span className="brandname">NovaPay</span></div><nav className="nav">{[['Overview','▦'],['Payment links','↗'],['Transactions','⇄'],['Developers','⌘'],['Webhooks','⌁']].map(([name,icon])=><button key={name} data-icon={icon} className={tab===name?'active':''} onClick={()=>setTab(name)}>{icon} <span className="navlabel">{name}</span></button>)}</nav><div className="sidefoot"><b>Test environment</b><br/>All payments are simulated. No real money is processed.</div></aside><main className="main"><header className="topbar"><div className="crumb">{tab}</div><div className="profile"><span>Test mode</span><div className="avatar">{user?.displayName?.[0]||'D'}</div><span>{user?.displayName||'Demo workspace'}</span>{firebaseEnabled&&<button className="btn" onClick={()=>user?signOut(auth!):signInWithPopup(auth!,new GoogleAuthProvider())}>{user?'Sign out':'Sign in'}</button>}</div></header><div className="content"><div className="heading"><div><h1>{tab==='Overview'?'Good evening 👋':tab}</h1><div className="sub">Here's what's happening with your payments today.</div></div><button className="btn primary" onClick={()=>setModal(true)}>＋ Create payment link</button></div>{tab==='Overview'&&<><div className="cards"><div className="card stat"><div className="statlabel">Successful volume <span>↗</span></div><div className="statvalue">₹{(total/100).toLocaleString('en-IN',{minimumFractionDigits:2})}</div><div className="positive">Test transactions only</div></div><div className="card stat"><div className="statlabel">Successful payments</div><div className="statvalue">{succeeded}</div><div className="muted" style={{fontSize:12}}>Across your payment links</div></div><div className="card stat"><div className="statlabel">Active payment links</div><div className="statvalue">{data.links.filter(l=>l.status==='ACTIVE').length}</div><div className="muted" style={{fontSize:12}}>Shareable checkout pages</div></div></div><section className="panel"><div className="panelhead"><h2>Recent transactions</h2><button className="btn" onClick={()=>setTab('Transactions')}>View all</button></div><Transactions payments={data.payments.slice(0,6)} refund={async(id:string)=>{await action({action:'refund',paymentId:id});notify('Refund simulated')}}/></section><section className="panel"><div className="panelhead"><h2>Payment links</h2><button className="btn" onClick={()=>setTab('Payment links')}>Manage links</button></div><Links links={data.links.slice(0,3)} notify={notify}/></section></>}
{tab==='Payment links'&&<section className="panel"><div className="panelhead"><h2>Your payment links</h2><button className="btn primary" onClick={()=>setModal(true)}>＋ New link</button></div><Links links={data.links} notify={notify}/></section>}
{tab==='Transactions'&&<section className="panel"><div className="panelhead"><h2>All transactions</h2><button className="btn" onClick={refresh}>Refresh</button></div><Transactions payments={data.payments} refund={async(id:string)=>{await action({action:'refund',paymentId:id});notify('Refund simulated')}}/></section>}
{tab==='Developers'&&<><div className="notice">These are demonstration credentials only. API keys are generated for display and are not currently used to authorize API requests.</div><section className="panel"><div className="panelhead"><h2>API keys</h2><button className="btn primary" onClick={key}>＋ Create test key</button></div>{secret&&<div className="notice">Copy your new key now: <b>{secret}</b><button className="btn" onClick={()=>{navigator.clipboard.writeText(secret);notify('Copied')}}>Copy</button></div>}{data.keys.length===0?<div className="empty">No API keys yet.</div>:data.keys.map(k=><div className="linkrow" style={{padding:'14px 0',borderBottom:'1px solid #f0f1f5'}} key={k.id}><div><b>{k.label}</b><div className="linkurl">{k.prefix}•••••••• · {k.revoked?'Revoked':'Active'}</div></div>{!k.revoked&&<button className="btn" onClick={async()=>{await action({action:'revokeKey',id:k.id});notify('Key revoked')}}>Revoke</button>}</div>)}</section><section className="panel"><h2>API quick start</h2><pre style={{whiteSpace:'pre-wrap',fontSize:12,background:'#f7f8fb',padding:15,borderRadius:9,overflowX:'auto'}}>{`// Demo API endpoint (dashboard actions only)
POST /api/demo
Content-Type: application/json

{ "action": "createLink", "title": "Order #123", "amount": 499 }`}</pre></section></>}
{tab==='Webhooks'&&<section className="panel"><div className="panelhead"><h2>Webhook event simulator</h2><button className="btn primary" onClick={async()=>{await action({action:'simulateWebhook',type:'payment.test'});notify('Test event generated')}}>＋ Send test event</button></div><div className="notice">Events are recorded locally in your database. No external webhook URL is called in this MVP.</div>{data.events.length===0?<div className="empty">No events yet. Complete a simulated checkout or send a test event.</div>:data.events.map(e=><div key={e.id} style={{padding:'13px 0',borderBottom:'1px solid #f0f1f5'}}><b style={{fontSize:13}}>{e.type}</b><div className="linkurl">{new Date(e.createdAt).toLocaleString()} · {e.delivered?'Recorded':'Pending'} · {e.id}</div><pre style={{fontSize:11,whiteSpace:'pre-wrap',background:'#f7f8fb',padding:10,borderRadius:8}}>{JSON.stringify(e.payload,null,2)}</pre></div>)}</section>}</div></main>{modal&&<div className="modalback" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h2>Create payment link</h2><div className="notice">Test mode: links create simulated transactions only.</div><div className="field"><label>What are you collecting payment for?</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Website design"/></div><div className="field"><label>Amount (INR)</label><input type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="499.00"/></div><div className="field"><label>Description (optional)</label><input value={desc} onChange={e=>setDesc(e.target.value)} placeholder="A short description"/></div><div className="actions"><button className="btn" onClick={()=>setModal(false)}>Cancel</button><button className="btn primary" onClick={create}>Create link</button></div></div></div>}{toast&&<div className="toast">{toast}</div>}</div>}
function Links({links,notify}:{links:any[];notify:(s:string)=>void}){return links.length===0?<div className="empty">No payment links yet. Create one to get started.</div>:<>{links.map(l=><div key={l.id} className="linkrow" style={{padding:'15px 0',borderBottom:'1px solid #f0f1f5'}}><div style={{minWidth:0}}><div className="linktitle">{l.title} <span className="pill">{l.status}</span></div><div className="linkurl">₹{(l.amount/100).toFixed(2)} · {l.payments.length} payments · {typeof window!=='undefined'?`${window.location.origin}/pay/${l.id}`:`/pay/${l.id}`}</div></div><div className="actions"><button className="btn" onClick={()=>{navigator.clipboard.writeText(`${window.location.origin}/pay/${l.id}`);notify('Payment link copied')}}>Copy link</button><a className="btn" href={`/pay/${l.id}`} target="_blank">Preview</a></div></div>)}</>}
function Transactions({payments,refund}:{payments:any[];refund:(id:string)=>void}){return payments.length===0?<div className="empty">No transactions yet. Create a payment link and run a test checkout.</div>:<div className="tablewrap"><table><thead><tr><th>Payment</th><th>Customer</th><th>Amount</th><th>Status</th><th>Date</th><th>Action</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td><b>{p.id.slice(-8).toUpperCase()}</b><div className="muted" style={{fontSize:11}}>{p.link?.title||'Test event'}</div></td><td>{p.customerEmail}</td><td className="amount">₹{(p.amount/100).toFixed(2)}</td><td><span className={`pill ${p.status==='FAILED'?'failed':p.status==='PENDING'?'pending':''}`}>{p.status}</span></td><td>{new Date(p.createdAt).toLocaleDateString()}</td><td>{p.status==='SUCCEEDED'?<button className="btn" onClick={()=>refund(p.id)}>Refund</button>:'—'}</td></tr>)}</tbody></table></div>}
